#include <asm/csr.h>
#include <asm/csr_bits/pmpcfg.h>
#include <asm/csr_bits/status.h>
#include <io/kbuild.h>
#include <sys/errno.h>
#include <uapi/komodo/memregions.h>
#include <uapi/komodo/smcapi.h>
#include <uapi/komodo/smccalls.h>
#include <uapi/komodo/svccalls.h>
#include "../monitor.h"

#define INDEX(sym, str, mem) \
        DEFINE(sym, offsetof(struct str, mem) / 8)

void asm_offsets(void)
{
    DEFINE(CONFIG_BOOT_CPU, CONFIG_BOOT_CPU);

    DEFINE(EXC_ECALL_S, EXC_ECALL_S);

    DEFINE(ENOSYS, ENOSYS);

    DEFINE(PMPCFG_A_TOR, PMPCFG_A_TOR);
    DEFINE(PMPCFG_R, PMPCFG_R);
    DEFINE(PMPCFG_W, PMPCFG_W);
    DEFINE(PMPCFG_X, PMPCFG_X);

    DEFINE(KOM_SMC_QUERY, KOM_SMC_QUERY);
    DEFINE(KOM_SMC_GETPHYSPAGES, KOM_SMC_GETPHYSPAGES);
    DEFINE(KOM_SMC_INIT_ADDRSPACE, KOM_SMC_INIT_ADDRSPACE);
    DEFINE(KOM_SMC_INIT_DISPATCHER, KOM_SMC_INIT_DISPATCHER);
    DEFINE(KOM_SMC_INIT_L2PTABLE, KOM_SMC_INIT_L2PTABLE);
    DEFINE(KOM_SMC_INIT_L3PTABLE, KOM_SMC_INIT_L3PTABLE);
    DEFINE(KOM_SMC_MAP_SECURE, KOM_SMC_MAP_SECURE);
    DEFINE(KOM_SMC_MAP_INSECURE, KOM_SMC_MAP_INSECURE);
    DEFINE(KOM_SMC_COPY_DATA, KOM_SMC_COPY_DATA);
    DEFINE(KOM_SMC_REMOVE, KOM_SMC_REMOVE);
    DEFINE(KOM_SMC_FINALISE, KOM_SMC_FINALISE);
    DEFINE(KOM_SMC_ENTER, KOM_SMC_ENTER);
    DEFINE(KOM_SMC_RESUME, KOM_SMC_RESUME);
    DEFINE(KOM_SMC_STOP, KOM_SMC_STOP);

    DEFINE(KOM_SVC_EXIT, KOM_SVC_EXIT);

    DEFINE(KOM_SECURE_NPAGES, KOM_SECURE_NPAGES);
    DEFINE(KOM_SECURE_RESERVE, KOM_SECURE_RESERVE);
    DEFINE(KOM_INSECURE_NPAGES, KOM_INSECURE_NPAGES);
    DEFINE(KOM_INSECURE_RESERVE, KOM_INSECURE_RESERVE);

    DEFINE(KOM_MAGIC, KOM_MAGIC);

    DEFINE(KOM_ERR_SUCCESS, KOM_ERR_SUCCESS);
    DEFINE(KOM_ERR_INVALID_PAGENO, KOM_ERR_INVALID_PAGENO);
    DEFINE(KOM_ERR_PAGEINUSE, KOM_ERR_PAGEINUSE);
    DEFINE(KOM_ERR_INVALID_ADDRSPACE, KOM_ERR_INVALID_ADDRSPACE);
    DEFINE(KOM_ERR_ALREADY_FINAL, KOM_ERR_ALREADY_FINAL);
    DEFINE(KOM_ERR_NOT_FINAL, KOM_ERR_NOT_FINAL);
    DEFINE(KOM_ERR_INVALID_MAPPING, KOM_ERR_INVALID_MAPPING);
    DEFINE(KOM_ERR_ADDRINUSE, KOM_ERR_ADDRINUSE);
    DEFINE(KOM_ERR_NOT_STOPPED, KOM_ERR_NOT_STOPPED);
    DEFINE(KOM_ERR_INTERRUPTED, KOM_ERR_INTERRUPTED);
    DEFINE(KOM_ERR_FAULT, KOM_ERR_FAULT);
    DEFINE(KOM_ERR_ALREADY_ENTERED, KOM_ERR_ALREADY_ENTERED);
    DEFINE(KOM_ERR_NOT_ENTERED, KOM_ERR_NOT_ENTERED);
    DEFINE(KOM_ERR_INVALID, KOM_ERR_INVALID);

    DEFINE(KOM_PAGE_FREE, KOM_PAGE_FREE);
    DEFINE(KOM_PAGE_ADDRSPACE, KOM_PAGE_ADDRSPACE);
    DEFINE(KOM_PAGE_DISPATCHER, KOM_PAGE_DISPATCHER);
    DEFINE(KOM_PAGE_L1PTABLE, KOM_PAGE_L1PTABLE);
    DEFINE(KOM_PAGE_L2PTABLE, KOM_PAGE_L2PTABLE);
    DEFINE(KOM_PAGE_L3PTABLE, KOM_PAGE_L3PTABLE);
    DEFINE(KOM_PAGE_DATA, KOM_PAGE_DATA);

    DEFINE(KOM_ADDRSPACE_INIT, KOM_ADDRSPACE_INIT);
    DEFINE(KOM_ADDRSPACE_FINAL, KOM_ADDRSPACE_FINAL);
    DEFINE(KOM_ADDRSPACE_STOPPED, KOM_ADDRSPACE_STOPPED);

    INDEX(KOM_ADDRSPACE_L1PT_PAGE, kom_addrspace, l1pt_page);
    INDEX(KOM_ADDRSPACE_REFCOUNT, kom_addrspace, refcount);
    INDEX(KOM_ADDRSPACE_STATE, kom_addrspace, state);

    INDEX(KOM_DISPATCHER_ENTERED, kom_dispatcher, entered);

    INDEX(KOM_DISPATCHER_REGS_RA, kom_dispatcher, regs.ra);
    INDEX(KOM_DISPATCHER_REGS_SP, kom_dispatcher, regs.sp);
    INDEX(KOM_DISPATCHER_REGS_GP, kom_dispatcher, regs.gp);
    INDEX(KOM_DISPATCHER_REGS_TP, kom_dispatcher, regs.tp);

    INDEX(KOM_DISPATCHER_REGS_T0, kom_dispatcher, regs.t0);
    INDEX(KOM_DISPATCHER_REGS_T1, kom_dispatcher, regs.t1);
    INDEX(KOM_DISPATCHER_REGS_T2, kom_dispatcher, regs.t2);

    INDEX(KOM_DISPATCHER_REGS_S0, kom_dispatcher, regs.s0);
    INDEX(KOM_DISPATCHER_REGS_S1, kom_dispatcher, regs.s1);

    INDEX(KOM_DISPATCHER_REGS_A0, kom_dispatcher, regs.a0);
    INDEX(KOM_DISPATCHER_REGS_A1, kom_dispatcher, regs.a1);
    INDEX(KOM_DISPATCHER_REGS_A2, kom_dispatcher, regs.a2);
    INDEX(KOM_DISPATCHER_REGS_A3, kom_dispatcher, regs.a3);
    INDEX(KOM_DISPATCHER_REGS_A4, kom_dispatcher, regs.a4);
    INDEX(KOM_DISPATCHER_REGS_A5, kom_dispatcher, regs.a5);
    INDEX(KOM_DISPATCHER_REGS_A6, kom_dispatcher, regs.a6);
    INDEX(KOM_DISPATCHER_REGS_A7, kom_dispatcher, regs.a7);

    INDEX(KOM_DISPATCHER_REGS_S2, kom_dispatcher, regs.s2);
    INDEX(KOM_DISPATCHER_REGS_S3, kom_dispatcher, regs.s3);
    INDEX(KOM_DISPATCHER_REGS_S4, kom_dispatcher, regs.s4);
    INDEX(KOM_DISPATCHER_REGS_S5, kom_dispatcher, regs.s5);
    INDEX(KOM_DISPATCHER_REGS_S6, kom_dispatcher, regs.s6);
    INDEX(KOM_DISPATCHER_REGS_S7, kom_dispatcher, regs.s7);
    INDEX(KOM_DISPATCHER_REGS_S8, kom_dispatcher, regs.s8);
    INDEX(KOM_DISPATCHER_REGS_S9, kom_dispatcher, regs.s9);
    INDEX(KOM_DISPATCHER_REGS_S10, kom_dispatcher, regs.s10);
    INDEX(KOM_DISPATCHER_REGS_S11, kom_dispatcher, regs.s11);

    INDEX(KOM_DISPATCHER_REGS_T3, kom_dispatcher, regs.t3);
    INDEX(KOM_DISPATCHER_REGS_T4, kom_dispatcher, regs.t4);
    INDEX(KOM_DISPATCHER_REGS_T5, kom_dispatcher, regs.t5);
    INDEX(KOM_DISPATCHER_REGS_T6, kom_dispatcher, regs.t6);

    INDEX(KOM_DISPATCHER_MEPC, kom_dispatcher, mepc);
    INDEX(KOM_DISPATCHER_SATP, kom_dispatcher, satp);
    INDEX(KOM_DISPATCHER_STVEC, kom_dispatcher, stvec);
    INDEX(KOM_DISPATCHER_SCOUNTEREN, kom_dispatcher, scounteren);
    INDEX(KOM_DISPATCHER_STVAL, kom_dispatcher, stval);
    INDEX(KOM_DISPATCHER_SIP, kom_dispatcher, sip);
    INDEX(KOM_DISPATCHER_SCAUSE, kom_dispatcher, scause);
    INDEX(KOM_DISPATCHER_SEPC, kom_dispatcher, sepc);
    INDEX(KOM_DISPATCHER_SSTATUS, kom_dispatcher, sstatus);
    INDEX(KOM_DISPATCHER_SSCRATCH, kom_dispatcher, sscratch);
    INDEX(KOM_DISPATCHER_SIE, kom_dispatcher, sie);

    DEFINE(_PAGE_PFN_SHIFT, _PAGE_PFN_SHIFT);
    DEFINE(_PAGE_TABLE, _PAGE_TABLE);
    DEFINE(_PAGE_ENCLAVE, _PAGE_ENCLAVE);
    DEFINE(_PAGE_RWX, _PAGE_READ | _PAGE_WRITE | _PAGE_EXEC);
    DEFINE(SATP_MODE_SV39, SATP_MODE_SV39);

    DEFINE(SR_TVM, SR_TVM);

    DEFINE(IE_SSIE, IE_SSIE);
    DEFINE(IE_STIE, IE_STIE);
    DEFINE(IE_SEIE, IE_SEIE);
}
