#pragma once

#include <io/const.h>
#include <asm/csr_bits/cause.h>

#define EDEL_INST_MISALIGNED    BIT_64(EXC_INST_MISALIGNED)
#define EDEL_INST_ACCESS        BIT_64(EXC_INST_ACCESS)
#define EDEL_ILLEGAL_INST       BIT_64(EXC_ILLEGAL_INST)
#define EDEL_BREAKPOINT         BIT_64(EXC_BREAKPOINT)
#define EDEL_LOAD_MISALIGNED    BIT_64(EXC_LOAD_MISALIGNED)
#define EDEL_LOAD_ACCESS        BIT_64(EXC_LOAD_ACCESS)
#define EDEL_STORE_MISALIGNED   BIT_64(EXC_STORE_MISALIGNED)
#define EDEL_STORE_ACCESS       BIT_64(EXC_STORE_ACCESS)
#define EDEL_ECALL_U            BIT_64(EXC_ECALL_U)
#define EDEL_ECALL_S            BIT_64(EXC_ECALL_S)
#define EDEL_ECALL_M            BIT_64(EXC_ECALL_M)
#define EDEL_INST_PAGE_FAULT    BIT_64(EXC_INST_PAGE_FAULT)
#define EDEL_LOAD_PAGE_FAULT    BIT_64(EXC_LOAD_PAGE_FAULT)
#define EDEL_STORE_PAGE_FAULT   BIT_64(EXC_STORE_PAGE_FAULT)
